// Package template generates safety documentation templates for go-FuSa projects.
//
// Use Generate to write one or all templates to a directory.
package template

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// Type identifies which safety documentation template to generate.
type Type string

const (
	TypeSafetyPlan     Type = "safety-plan"
	TypeTestEvidence   Type = "test-evidence"
	TypeHARA           Type = "hara"
	TypeSDP            Type = "sdp"
	TypeSVP            Type = "svp"
	TypeSCMP           Type = "scmp"
	TypeSQAP           Type = "sqap"
	TypeIEC61508FSP    Type = "iec61508-fsp"
	TypeISO26262FMEA   Type = "iso26262-fmea"
	TypeAll            Type = "all"
)

// Generate writes the named template file(s) to dir.
// It returns an error if a target file already exists or cannot be written.
//
//fusa:req REQ-CLI010
func Generate(dir string, t Type) error {
	switch t {
	case TypeSafetyPlan:
		return write(dir, "SAFETY_PLAN.md", safetyPlan())
	case TypeTestEvidence:
		return write(dir, "TEST_EVIDENCE.md", testEvidence())
	case TypeHARA:
		return write(dir, "HARA.md", hara())
	case TypeSDP:
		return write(dir, "SAFETY_PLAN.md", sdp())
	case TypeSVP:
		return write(dir, "SVP.md", svp())
	case TypeSCMP:
		return write(dir, "SCMP.md", scmp())
	case TypeSQAP:
		return write(dir, "SQAP.md", sqap())
	case TypeIEC61508FSP:
		return write(dir, "IEC61508-FSP.md", iec61508FSP())
	case TypeISO26262FMEA:
		return write(dir, "ISO26262-FMEA.md", iso26262FMEA())
	case TypeAll:
		for _, pair := range []struct {
			name    string
			content string
		}{
			{"SAFETY_PLAN.md", safetyPlan()},
			{"TEST_EVIDENCE.md", testEvidence()},
			{"HARA.md", hara()},
			{"SVP.md", svp()},
			{"SCMP.md", scmp()},
			{"SQAP.md", sqap()},
			{"IEC61508-FSP.md", iec61508FSP()},
			{"ISO26262-FMEA.md", iso26262FMEA()},
		} {
			if err := write(dir, pair.name, pair.content); err != nil {
				return err
			}
		}
		return nil
	default:
		return fmt.Errorf("template: unknown type %q", t)
	}
}

func write(dir, name, content string) error {
	path := filepath.Join(dir, name)
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("template: %s already exists; delete it to regenerate", path)
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("template: mkdir %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o640); err != nil {
		return fmt.Errorf("template: write %s: %w", path, err)
	}
	return nil
}

func today() string { return time.Now().UTC().Format("2006-01-02") }

func sdp() string {
	return fmt.Sprintf("# Software Development Plan (SDP)\n"+
		"<!-- Generated by go-FuSa on %s — DO-178C §11.1 -->\n\n"+
		"## 1. Purpose\n\nDescribe the purpose and scope of this SDP.\n\n"+
		"## 2. Software Overview\n\n"+
		"| Field | Value |\n|---|---|\n| Project | |\n| Part Number | |\n| DAL | |\n| Standard | DO-178C |\n\n"+
		"## 3. Software Lifecycle\n\nDescribe the lifecycle model (e.g. iterative, waterfall). "+
		"Map to phases: planning, development, integration, verification, CM, QA.\n\n"+
		"## 4. Software Development Environment\n\nList compilers, tools, hardware targets, "+
		"and OS. Include version numbers. Reference tool qualification records.\n\n"+
		"## 5. Coding Standards\n\nReference the coding standards applied. "+
		"go-FuSa enforces standards via %s (lint) and %s (analysis).\n\n"+
		"## 6. Traceability\n\nRequirements traceable via %s. "+
		"Source annotated with %s. Tests annotated with %s.\n\n"+
		"## 7. Deviations\n\nList any approved deviations from DO-178C objectives.\n\n"+
		"## 8. Approvals\n\n"+
		"| Role | Name | Date |\n|---|---|---|\n| Software Lead | | |\n| Safety Engineer | | |\n",
		today(),
		bt("gofusa lint"), bt("gofusa analyze"),
		bt("gofusa trace"), bt("//fusa:req"), bt("//fusa:test"),
	)
}

func svp() string {
	return fmt.Sprintf("# Software Verification Plan (SVP)\n"+
		"<!-- Generated by go-FuSa on %s — DO-178C §11.3 -->\n\n"+
		"## 1. Purpose\n\nDescribe verification activities, methods, independence requirements, "+
		"and pass/fail criteria.\n\n"+
		"## 2. Verification Methods\n\n"+
		"| Method | Tool | DAL Applicability |\n|---|---|---|\n"+
		"| Static analysis | %s | DAL-A/B/C/D |\n"+
		"| Structural coverage | %s | DAL-A/B/C |\n"+
		"| Requirement-based testing | %s | DAL-A/B/C/D |\n\n"+
		"## 3. Independence\n\nAt DAL-A/B: verification must be performed by a person or tool "+
		"independent of the developer. Document assignment of independent verifier.\n\n"+
		"## 4. Coverage Objectives\n\n"+
		"| DAL | Statement | Decision | MC/DC |\n|---|---|---|---|\n"+
		"| DAL-A | 100%% | 100%% | 100%% |\n"+
		"| DAL-B | 100%% | 100%% | — |\n"+
		"| DAL-C | 100%% | — | — |\n\n"+
		"Coverage measured by %s.\n\n"+
		"## 5. Regression Strategy\n\nAll tests re-run on every commit via CI (%s).\n\n"+
		"## 6. Approvals\n\n"+
		"| Role | Name | Date |\n|---|---|---|\n| Verification Lead | | |\n",
		today(),
		bt("gofusa check"), bt("gofusa coverage"),
		bt("gofusa verify"),
		bt("gofusa coverage"), bt("gofusa verify"),
	)
}

func scmp() string {
	return fmt.Sprintf("# Software Configuration Management Plan (SCMP)\n"+
		"<!-- Generated by go-FuSa on %s — DO-178C §11.4 -->\n\n"+
		"## 1. Purpose\n\nDefine the configuration management process for all software lifecycle data.\n\n"+
		"## 2. Configuration Items\n\nAll items listed in the Software Configuration Index (%s).\n\n"+
		"## 3. Baseline Management\n\nBaselines created at: planning complete, first test, "+
		"certification submittal. Each baseline produces a signed SCI and audit pack.\n\n"+
		"## 4. Change Control\n\nAll changes via pull request. Require review by CODEOWNERS. "+
		"CI must pass before merge. Each change generates a new %s entry.\n\n"+
		"## 5. Archive and Retrieval\n\nLifecycle data archived via %s. "+
		"Checksums recorded in %s.\n\n"+
		"## 6. Problem Reporting\n\nProblem reports tracked in %s per DO-178C §11.17.\n\n"+
		"## 7. Approvals\n\n"+
		"| Role | Name | Date |\n|---|---|---|\n| CM Lead | | |\n",
		today(),
		bt("sci.json"),
		bt(".fusa-problems.json"),
		bt("gofusa audit-pack"), bt("sci.json"),
		bt(".fusa-problems.json"),
	)
}

func sqap() string {
	return fmt.Sprintf("# Software Quality Assurance Plan (SQAP)\n"+
		"<!-- Generated by go-FuSa on %s — DO-178C §11.5 -->\n\n"+
		"## 1. Purpose\n\nDefine QA activities that provide assurance the software lifecycle "+
		"is executed in accordance with approved plans and standards.\n\n"+
		"## 2. QA Activities\n\n"+
		"| Activity | Frequency | go-FuSa Command |\n|---|---|---|\n"+
		"| Coding standards review | Every PR | %s |\n"+
		"| Static analysis | Every PR | %s |\n"+
		"| Requirement traceability audit | Every release | %s |\n"+
		"| Coverage gate | Every commit | %s |\n"+
		"| DO-178C gap review | Every release | %s |\n"+
		"| SAS review | Pre-submittal | %s |\n\n"+
		"## 3. Non-conformance Tracking\n\nNon-conformances logged in %s. "+
		"Critical items block release.\n\n"+
		"## 4. QA Independence\n\nQA reviews performed by personnel independent of the developer.\n\n"+
		"## 5. Approvals\n\n"+
		"| Role | Name | Date |\n|---|---|---|\n| QA Lead | | |\n| Safety Engineer | | |\n",
		today(),
		bt("gofusa lint"),
		bt("gofusa analyze"),
		bt("gofusa trace"),
		bt("gofusa coverage"),
		bt("gofusa do178"),
		bt("gofusa sas"),
		bt(".fusa-problems.json"),
	)
}

// bt wraps s in backtick characters for use inside raw string literals.
func bt(s string) string { return "`" + s + "`" }

func safetyPlan() string {
	return fmt.Sprintf("# Safety Plan\n"+
		"<!-- Generated by go-FuSa on %s -->\n\n"+
		"## Project Information\n\n"+
		"| Field          | Value |\n"+
		"|----------------|-------|\n"+
		"| Project Name   |       |\n"+
		"| Standard       |       |\n"+
		"| ASIL/SIL Level |       |\n"+
		"| Safety Manager |       |\n"+
		"| Review Date    |       |\n\n"+
		"## Scope\n\n"+
		"Describe the item under development, its intended use, and the safety-relevant\n"+
		"operational environment.\n\n"+
		"## Safety Goals\n\n"+
		"| ID     | Safety Goal | ASIL/SIL |\n"+
		"|--------|-------------|----------|\n"+
		"| SG-001 |             |          |\n\n"+
		"## Safety Measures\n\n"+
		"| ID     | Measure Description | Linked Goal |\n"+
		"|--------|---------------------|-------------|\n"+
		"| SM-001 |                     | SG-001      |\n\n"+
		"## Evidence Plan\n\n"+
		"- [ ] Static analysis report (%s)\n"+
		"- [ ] Coding standard compliance (%s)\n"+
		"- [ ] Requirement traceability matrix (%s)\n"+
		"- [ ] Test coverage report (%s)\n"+
		"- [ ] SBOM (%s)\n"+
		"- [ ] Build provenance (%s)\n\n"+
		"## Review and Approval\n\n"+
		"| Role            | Name | Signature | Date |\n"+
		"|-----------------|------|-----------|------|\n"+
		"| Safety Engineer |      |           |      |\n"+
		"| Project Manager |      |           |      |\n",
		today(),
		bt("gofusa analyze"),
		bt("gofusa lint"),
		bt("gofusa trace"),
		bt("gofusa verify"),
		bt("gofusa release"),
		bt("gofusa release"),
	)
}

func testEvidence() string {
	return fmt.Sprintf("# Test Evidence\n"+
		"<!-- Generated by go-FuSa on %s -->\n\n"+
		"## Test Execution Summary\n\n"+
		"| Field         | Value |\n"+
		"|---------------|-------|\n"+
		"| Test Date     |       |\n"+
		"| Go Version    |       |\n"+
		"| Platform      |       |\n"+
		"| Total Tests   |       |\n"+
		"| Passed        |       |\n"+
		"| Failed        |       |\n"+
		"| Skipped       |       |\n"+
		"| Coverage (%%) |       |\n\n"+
		"## Test Environment\n\n"+
		"Describe the hardware and software environment used during test execution.\n\n"+
		"## Requirement Traceability\n\n"+
		"| Req ID | Description | Test(s) | Result |\n"+
		"|--------|-------------|---------|--------|\n"+
		"|        |             |         |        |\n\n"+
		"## Regression Evidence\n\n"+
		"Generated by %s. Attach the coverage.out and test output logs.\n\n"+
		"## Anomalies\n\n"+
		"List any test failures, deviations, or waived requirements with justification.\n",
		today(),
		bt("gofusa verify"),
	)
}

func hara() string {
	return fmt.Sprintf("# Hazard Analysis and Risk Assessment (HARA)\n"+
		"<!-- Generated by go-FuSa on %s -->\n\n"+
		"Reference: ISO 26262-3:2018 Clause 6 / IEC 61508-1 Clause 7.4\n\n"+
		"## Operational Situations\n\n"+
		"| ID     | Situation Description |\n"+
		"|--------|-----------------------|\n"+
		"| OS-001 |                       |\n\n"+
		"## Hazard Identification\n\n"+
		"| ID    | Hazard Description | Source | Operational Situation |\n"+
		"|-------|--------------------|--------|-----------------------|\n"+
		"| H-001 |                    |        | OS-001                |\n\n"+
		"## Risk Assessment\n\n"+
		"| Hazard | Severity (S) | Exposure (E) | Controllability (C) | ASIL |\n"+
		"|--------|-------------|--------------|---------------------|------|\n"+
		"| H-001  | S?          | E?           | C?                  | ?    |\n\n"+
		"Severity: S0-S3 | Exposure: E0-E4 | Controllability: C0-C3\n\n"+
		"## Safety Goals\n\n"+
		"| ID     | Description | Linked Hazard | ASIL |\n"+
		"|--------|-------------|---------------|------|\n"+
		"| SG-001 |             | H-001         | ?    |\n\n"+
		"## Safe States\n\n"+
		"| Safety Goal | Safe State Description |\n"+
		"|-------------|------------------------|\n"+
		"| SG-001      |                        |\n",
		today(),
	)
}

func iec61508FSP() string {
	return fmt.Sprintf("# IEC 61508 Functional Safety Plan (FSP)\n"+
		"<!-- Generated by go-FuSa on %s — IEC 61508-1 §6 -->\n\n"+
		"## 1. Purpose\n\nDefine the functional safety management activities for this E/E/PE "+
		"safety-related system in accordance with IEC 61508.\n\n"+
		"## 2. Project Scope\n\n"+
		"| Field                  | Value |\n|------------------------|-------|\n"+
		"| System Name            |       |\n"+
		"| SIL Target             |       |\n"+
		"| Standard               | IEC 61508:2010 |\n"+
		"| Safety Manager         |       |\n"+
		"| Review Date            |       |\n\n"+
		"## 3. Safety Lifecycle\n\nIEC 61508 requires a defined safety lifecycle. "+
		"This project follows the phases defined in IEC 61508-1 §6:\n\n"+
		"| Phase | Description | go-FuSa Evidence |\n|-------|-------------|------------------|\n"+
		"| Concept | Hazard identification and risk assessment | HARA.md |\n"+
		"| Overall scope definition | System/software boundary | boundary.mermaid |\n"+
		"| Hazard and risk analysis | SIL determination | HARA.md |\n"+
		"| Overall safety requirements | SRS | .fusa-reqs.json |\n"+
		"| Safety requirements allocation | Software SRS | .fusa-reqs.json |\n"+
		"| Software development | Implementation and V&V | check-report.json |\n"+
		"| Overall installation and commissioning | | |\n"+
		"| Overall safety validation | | .fusa-evidence.json |\n"+
		"| Overall operation, maintenance, repair | | |\n"+
		"| Decommissioning | | |\n\n"+
		"## 4. Safety Integrity Level (SIL) Determination\n\nDocument the risk graph or "+
		"LOPA analysis used to determine the required SIL. Reference HARA.md.\n\n"+
		"## 5. Functional Safety Management\n\n"+
		"| Activity | Responsibility | Evidence |\n|----------|---------------|----------|\n"+
		"| Functional Safety Assessment | Safety Engineer | |\n"+
		"| Configuration Management | CM Lead | %s |\n"+
		"| Problem Reporting | Team Lead | %s |\n"+
		"| Tool Qualification | V&V Engineer | %s |\n\n"+
		"## 6. Verification and Validation Plan\n\nRefer to %s for V&V activities, "+
		"methods, and independence requirements.\n\n"+
		"## 7. Approvals\n\n"+
		"| Role | Name | Signature | Date |\n|------|------|-----------|------|\n"+
		"| Safety Engineer | | | |\n"+
		"| Project Manager | | | |\n",
		today(),
		bt("sbom.json"),
		bt(".fusa-problems.json"),
		bt("qualify-report.json"),
		bt("SVP.md"),
	)
}

func iso26262FMEA() string {
	return fmt.Sprintf("# ISO 26262 FMEA Worksheet\n"+
		"<!-- Generated by go-FuSa on %s — ISO 26262-9:2018 §8 -->\n\n"+
		"## 1. Purpose\n\nThis document provides a Failure Mode and Effects Analysis (FMEA) for "+
		"the software item under ISO 26262. It identifies potential failure modes, their effects, "+
		"detection controls, and safety mechanisms.\n\n"+
		"Reference: ISO 26262-9:2018 §8 — Analysis techniques (FMEA/FMECA).\n\n"+
		"## 2. Item Description\n\n"+
		"| Field              | Value |\n|--------------------|-------|\n"+
		"| Item Name          |       |\n"+
		"| Part Number        |       |\n"+
		"| ASIL               |       |\n"+
		"| Hardware Version   |       |\n"+
		"| Software Version   |       |\n\n"+
		"## 3. FMEA Table\n\n"+
		"<!-- Auto-populate from gofusa fmea output (fmea.json) -->\n\n"+
		"| ID | Function | Failure Mode | Effect (Local) | Effect (System) | ASIL | Severity | "+
		"Detection Method | Safety Mechanism | Residual Risk | Action |\n"+
		"|----|----------|--------------|----------------|-----------------|------|----------|-"+
		"--------------------|-------------------|---------------|--------|\n"+
		"| FM-001 | | | | | | S? | | | | |\n\n"+
		"Severity Classes: S0=No injuries, S1=Light injuries, S2=Serious injuries, S3=Life-threatening\n\n"+
		"## 4. Summary\n\n"+
		"| ASIL | Total Failure Modes | Mitigated | Residual |\n"+
		"|------|---------------------|-----------|----------|\n"+
		"| ASIL-A | | | |\n"+
		"| ASIL-B | | | |\n"+
		"| ASIL-C | | | |\n"+
		"| ASIL-D | | | |\n\n"+
		"## 5. Review and Approval\n\n"+
		"| Role | Name | Date |\n|------|------|------|\n"+
		"| Safety Engineer | | |\n"+
		"| System Engineer | | |\n\n"+
		"<!-- Link to machine-generated FMEA: gofusa fmea > fmea.json -->\n",
		today(),
	)
}
