// Package template generates safety documentation templates for go-FuSa projects.
//
// Use Generate to write one or all templates to a directory.
package template

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// Type identifies which safety documentation template to generate.
type Type string

const (
	TypeSafetyPlan   Type = "safety-plan"
	TypeTestEvidence Type = "test-evidence"
	TypeHARA         Type = "hara"
	TypeAll          Type = "all"
)

// Generate writes the named template file(s) to dir.
// It returns an error if a target file already exists or cannot be written.
func Generate(dir string, t Type) error {
	switch t {
	case TypeSafetyPlan:
		return write(dir, "SAFETY_PLAN.md", safetyPlan())
	case TypeTestEvidence:
		return write(dir, "TEST_EVIDENCE.md", testEvidence())
	case TypeHARA:
		return write(dir, "HARA.md", hara())
	case TypeAll:
		for _, pair := range []struct {
			name    string
			content string
		}{
			{"SAFETY_PLAN.md", safetyPlan()},
			{"TEST_EVIDENCE.md", testEvidence()},
			{"HARA.md", hara()},
		} {
			if err := write(dir, pair.name, pair.content); err != nil {
				return err
			}
		}
		return nil
	default:
		return fmt.Errorf("template: unknown type %q", t)
	}
}

func write(dir, name, content string) error {
	path := filepath.Join(dir, name)
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("template: %s already exists; delete it to regenerate", path)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("template: mkdir %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("template: write %s: %w", path, err)
	}
	return nil
}

func today() string { return time.Now().UTC().Format("2006-01-02") }

// bt wraps s in backtick characters for use inside raw string literals.
func bt(s string) string { return "`" + s + "`" }

func safetyPlan() string {
	return fmt.Sprintf("# Safety Plan\n"+
		"<!-- Generated by go-FuSa on %s -->\n\n"+
		"## Project Information\n\n"+
		"| Field          | Value |\n"+
		"|----------------|-------|\n"+
		"| Project Name   |       |\n"+
		"| Standard       |       |\n"+
		"| ASIL/SIL Level |       |\n"+
		"| Safety Manager |       |\n"+
		"| Review Date    |       |\n\n"+
		"## Scope\n\n"+
		"Describe the item under development, its intended use, and the safety-relevant\n"+
		"operational environment.\n\n"+
		"## Safety Goals\n\n"+
		"| ID     | Safety Goal | ASIL/SIL |\n"+
		"|--------|-------------|----------|\n"+
		"| SG-001 |             |          |\n\n"+
		"## Safety Measures\n\n"+
		"| ID     | Measure Description | Linked Goal |\n"+
		"|--------|---------------------|-------------|\n"+
		"| SM-001 |                     | SG-001      |\n\n"+
		"## Evidence Plan\n\n"+
		"- [ ] Static analysis report (%s)\n"+
		"- [ ] Coding standard compliance (%s)\n"+
		"- [ ] Requirement traceability matrix (%s)\n"+
		"- [ ] Test coverage report (%s)\n"+
		"- [ ] SBOM (%s)\n"+
		"- [ ] Build provenance (%s)\n\n"+
		"## Review and Approval\n\n"+
		"| Role            | Name | Signature | Date |\n"+
		"|-----------------|------|-----------|------|\n"+
		"| Safety Engineer |      |           |      |\n"+
		"| Project Manager |      |           |      |\n",
		today(),
		bt("gofusa analyze"),
		bt("gofusa lint"),
		bt("gofusa trace"),
		bt("gofusa verify"),
		bt("gofusa release"),
		bt("gofusa release"),
	)
}

func testEvidence() string {
	return fmt.Sprintf("# Test Evidence\n"+
		"<!-- Generated by go-FuSa on %s -->\n\n"+
		"## Test Execution Summary\n\n"+
		"| Field         | Value |\n"+
		"|---------------|-------|\n"+
		"| Test Date     |       |\n"+
		"| Go Version    |       |\n"+
		"| Platform      |       |\n"+
		"| Total Tests   |       |\n"+
		"| Passed        |       |\n"+
		"| Failed        |       |\n"+
		"| Skipped       |       |\n"+
		"| Coverage (%%) |       |\n\n"+
		"## Test Environment\n\n"+
		"Describe the hardware and software environment used during test execution.\n\n"+
		"## Requirement Traceability\n\n"+
		"| Req ID | Description | Test(s) | Result |\n"+
		"|--------|-------------|---------|--------|\n"+
		"|        |             |         |        |\n\n"+
		"## Regression Evidence\n\n"+
		"Generated by %s. Attach the coverage.out and test output logs.\n\n"+
		"## Anomalies\n\n"+
		"List any test failures, deviations, or waived requirements with justification.\n",
		today(),
		bt("gofusa verify"),
	)
}

func hara() string {
	return fmt.Sprintf("# Hazard Analysis and Risk Assessment (HARA)\n"+
		"<!-- Generated by go-FuSa on %s -->\n\n"+
		"Reference: ISO 26262-3:2018 Clause 6 / IEC 61508-1 Clause 7.4\n\n"+
		"## Operational Situations\n\n"+
		"| ID     | Situation Description |\n"+
		"|--------|-----------------------|\n"+
		"| OS-001 |                       |\n\n"+
		"## Hazard Identification\n\n"+
		"| ID    | Hazard Description | Source | Operational Situation |\n"+
		"|-------|--------------------|--------|-----------------------|\n"+
		"| H-001 |                    |        | OS-001                |\n\n"+
		"## Risk Assessment\n\n"+
		"| Hazard | Severity (S) | Exposure (E) | Controllability (C) | ASIL |\n"+
		"|--------|-------------|--------------|---------------------|------|\n"+
		"| H-001  | S?          | E?           | C?                  | ?    |\n\n"+
		"Severity: S0-S3 | Exposure: E0-E4 | Controllability: C0-C3\n\n"+
		"## Safety Goals\n\n"+
		"| ID     | Description | Linked Hazard | ASIL |\n"+
		"|--------|-------------|---------------|------|\n"+
		"| SG-001 |             | H-001         | ?    |\n\n"+
		"## Safe States\n\n"+
		"| Safety Goal | Safe State Description |\n"+
		"|-------------|------------------------|\n"+
		"| SG-001      |                        |\n",
		today(),
	)
}
